
ALTER USER postgres WITH PASSWORD 'pass';
-- DROP DATABASE IF EXISTS test;
-- CREATE DATABASE postgreDB;
-- -- CREATE USER IF NOT EXISTS '$POSTGRES_USER'@'%' IDENTIFIED BY 'POSTGRES_PASSWORD';
-- CREATE USER "$POSTGRES_USER" WITH PASSWORD '$POSTGRES_PASSWORD';
-- CREATE USER root WITH PASSWORD '$POSTGRES_ROOT_PASSWORD';

-- -- GRANT ALL PRIVILEGES ON *.* TO '$POSTGRES_USER'@'%';
-- GRANT ALL PRIVILEGES ON DATABASE postgreDB TO "$POSTGRES_USER";
-- -- SET PASSWORD FOR 'root'@'$POSTGRES_HOST' = PASSWORD('$POSTGRES_ROOT_PASSWORD');
-- -- ALTER USER root WITH PASSWORD '$POSTGRES_ROOT_PASSWORD';

-- -- FLUSH PRIVILEGES;
-- CREATE TABLE users (
--     nickname        varchar(20),
--     user_password   varchar(20),
--     user_login      varchar(20)
-- );

-- CREATE TABLE score (
--     win     int,
--     loose   int
-- );